export enum RabbitMQQueueProducts {
  CREATE_PRODUCTS = 'CREATE_PRODUCTS',
  FIND_ALL_PRODUCTS = 'FIND_ALL_PRODUCTS',
  FIND_PRODUCT_BY_ID = 'FIND_PRODUCT_BY_ID',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
}

export enum RabbitMQQueueInventory {
  CREATE_INVENTORY = 'CREATE_INVENTORY',
  PRODUCT_INVENTORY = 'PRODUCT_INVENTORY',
  UPDATE_INVENTORY = 'UPDATE_INVENTORY',
  DELETE_INVENTORY = 'DELETE_INVENTORY',
}
